name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: cmake generate
      run: |
        mkdir antsbin
        cd antsbin
        cmake ../
    - name: make
      run: make -j 8
