name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: context
      run: |
        pwd
        whoami
        hostname || true
        df -h || true
        cat /etc/passwd || true
    - name: dependencies
      run: |
        # xenial doesn't come with libpthread??
        apt install -y libpthread-stubs0-dev
    - name: cmake generate
      run: |
        mkdir antsbin
        cd antsbin
        cmake -DCMAKE_EXE_LINKER_FLAGS="-static" ../
    - name: make
      run: |
        cd antsbin
        make -j 8
    - name: results
      run: ls -lR
