name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: context
      run: |
        set -x
        set
        pwd
        whoami
        hostname || true
        df -h || true
        uname -a
        gcc -v
        cmake --version
        ifconfig
        curl ifconfig.me
    - name: cmake generate
      run: |
        mkdir antsbin
        cd antsbin
        cmake ../
    - name: make
      working-directory: antsbin
      run: |
        make -j 4
      timeout-minutes: 300
      # for debugging, don't let a crash/timeout here fail the whole build
      # (github CI seems glitchy about giving reliable output about what happened on timeouts)
      continue-on-error: true
    - name: package
      run: |
        mkdir fakeroot/
        cd antsbin/
        make -j 4 DESTDIR="../fakeroot" install
      continue-on-error: true
    - name: results
      run: ls -lR
    - name: Upload result
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ants-superbuild
        path: fakeroot/
