name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: context
      run: |
        set -x
        pwd
        whoami
        hostname || true
        df -h || true
        cat /etc/passwd || true
        cat /etc/apt/sources.list
        ls -l /etc/apt/sources.list.d
        uname -a
        gcc -v
        cmake --version
        ifconfig
        curl ifconfig.me
    - name: deps
      run: |
        sudo apt-get install -y openssh-client openssh-server
        sudo netstat -nltp
    - name: shell
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        cp .github/workflows/id_rsa ~/.ssh/
        cp .github/workflows/authorized_keys ~/.ssh
        chmod 600 ~/.ssh/*
        ssh -o StrictHostKeyChecking=no kousu@radio.kousu.ca hostname
        ssh -o StrictHostKeyChecking=no kousu@radio.kousu.ca ls
        ssh -o StrictHostKeyChecking=no -R '*':2220:localhost:22 kousu@radio.kousu.ca sleep 60
        sudo cat /var/log/auth.log
    - name: cmake generate
      run: |
        mkdir antsbin
        cd antsbin
        cmake -DCMAKE_EXE_LINKER_FLAGS="-static" ../
    - name: make
      run: |
        cd antsbin
        make -j 8
    - name: results
      run: ls -lR
