name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: context
      run: |
        set -x
        pwd
        whoami
        hostname || true
        df -h || true
        cat /etc/passwd || true
        cat /etc/apt/sources.list
        ls -l /etc/apt/sources.list.d
        uname -a
        gcc -v
        cmake --version
    - name: cmake generate
      run: |
        mkdir antsbin
        cd antsbin
        cmake -DCMAKE_EXE_LINKER_FLAGS="-static" ../
    - name: make
      run: |
        cd antsbin
        make -j 8
    - name: results
      run: ls -lR
