name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: context
      run: |
        set -x
        set
        pwd
        whoami
        hostname || true
        df -h || true
        uname -a
        gcc -v
        cmake --version
        ifconfig
        curl ifconfig.me
    - name: cmake generate
      run: |
        mkdir antsbin
        cd antsbin
        cmake \
          -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_TESTING=OFF \
          -DANTS_USE_QT=OFF \
          -DANTS_INSTALL_DEVELOPMENT=OFF \
          -DCOPY_SCRIPT_FILES_TO_BIN_DIR=OFF \
          -DANTS_BUILD_DISTRIBUTE=ON \
          -DBUILD_ALL_ANTS_APPS=ON \
          -DRUN_LONG_TESTS=OFF \
          -DRUN_SHORT_TESTS=OFF \
          -DUSE_VTK=OFF \
          ../
    - name: make
      working-directory: antsbin
      run: |
        make VERBOSE=1 -j 4
      timeout-minutes: 300
      # for debugging, don't let a crash/timeout here fail the whole build
      # (github CI seems glitchy about giving reliable output about what happened on timeouts)
      continue-on-error: true
    - name: package
      run: |
        mkdir fakeroot/
        cd antsbin/
        make VERBOSE=1 -j 4 DESTDIR="../fakeroot" install
      continue-on-error: true
    - name: results
      working-directory: antsbin
      run: find .
    - name: Upload result
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ants-superbuild
        #path: fakeroot/ # TODO, once I figure out why make install doesn't work
        path: antsbin/ANTS-build
