name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-alt: # Github only supports Ubuntu natively; for other Linuxes, we need to use Docker
    strategy:
      matrix:
        os: ['centos', 'archlinux']
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    steps:
    - name: install toolchain
      if: contains(matrix.os, 'centos')
      run: |
        yum install -y make cmake gcc gcc-c++ git zlib-devel
    - name: install toolchain
      if: contains(matrix.os, 'archlinux')
      run: |
        pacman -Syy --noconfirm make cmake gcc git libffi
    - uses: actions/checkout@v1
    - name: package
      run: |
        mkdir sct-apps
        uname -a > sct-apps/platform.txt
        tar -zcvf sct-apps.tar.gz sct-apps/
      continue-on-error: true
    - name: results (DEBUG)
      run: find .
    - name: Upload result
      uses: actions/upload-artifact@v2-preview
      with:
        # there's a lurking bug here: Artifacts can't have ':' in their names,
        # but docker images are named with colons in their names to specify specific versions
        # so if we want to maintain an old "centos:7", say, we're stuck.
        # it's okay for now though.
        name: ants-superbuild_${{ matrix.os }}
        #path: fakeroot/ # this is 2.3G large in this build
        path: sct-apps.tar.gz

  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: package
      run: |
        mkdir sct-apps
        uname -a > sct-apps/platform.txt
        tar -zcvf sct-apps.tar.gz sct-apps/
      continue-on-error: true
    - name: results (DEBUG)
      run: find .
    - name: Upload result
      uses: actions/upload-artifact@v2-preview
      with:
        name: ants-superbuild_${{ matrix.os }}
        #path: fakeroot/ # this is 2.3G large in this build
        path: sct-apps.tar.gz
  
  release:
    needs: [build-alt, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: ants-superbuild_centos:8
      - uses: actions/download-artifact@v1
        with:
          name: ants-superbuild_archlinux 
      - uses: actions/download-artifact@v1
        with:
          name: ants-superbuild_ubuntu-16.04
      - uses: actions/download-artifact@v1
        with:
          name: ants-superbuild_ubuntu-18.04
      - uses: actions/download-artifact@v1
        with:
          name: ants-superbuild_macos-latest
      - name: check results
        run: |
           find .
